program: place_cell_tpc_sweep.py
project: tpc_sweep_kaiming_uniform
name: search_v0
method: bayes

metric:
  goal: minimize
  name: loss

parameters:
  learning_rate:
    distribution: log_uniform_values
    min: 0.000005
    max: 0.0001
  inf_lr:
    distribution: log_uniform_values
    min: 0.001
    max: 0.1
    
early_terminate:
  type: hyperband
  min_iter: 10

command:
- python
- ${program}
- --sequence_length
- "10"
- --batch_size
- "1"
- --n_steps 
- "1000"
- --n_epochs
- "100"
- --save
- "False"
- --out_activation
- "softmax"
- --rec_activation
- "relu"
- --loss
- "CE"
- --is_wandb
- "True"
- --sweep
- "True"
- --inf_iters
- "5"
- --weight_init
- "kaiming_normal"